name: Code Butler

on:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Code Butler
      uses: ouchi2501/code-butler@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        command: review
