name: Code Butler

on:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Code Butler
      uses: reviewdog/action-reviewdog@v1
      with:
        github_token: ${{ '{{' }} secrets.GITHUB_TOKEN {{ '}}' }}
        reporter: github-pr-review # Change as necessary to match how 'review' is expected to be handled
        tool: 'eslint' # or any other linter that's required
